#!/usr/bin/env php
<?php

use Nayjest\WorkerControl\WorkerControlCommand;
use Symfony\Component\Console\Application;

$bootstrapPaths = [
    __DIR__ . '/vendor/autoload.php', # Standalone
    __DIR__ . '/../../../src/bootstrap.php', # Lib
    __DIR__ . '/../../autoload.php', # Lib

];

$loader = null;
foreach($bootstrapPaths as $path) {
    if (file_exists($path)) {
        $loader = $path;
        break;
    }
}
if (!$loader) {
    throw new RuntimeException("PHP auto-loader not found. Run 'composer install'");
}
require_once $loader;

$app = new Application();
$command = new WorkerControlCommand(
    getenv('DEFAULT_WORKER_COMMAND'),
    getenv('DEFAULT_WORKER_QTY')?:1,
    getenv('DEFAULT_WORKER_DIR')
);
$app->add($command);
$app->setDefaultCommand($command->getName(), true);
$app->run();